version: "3"
services:
  directus:
    image: directus/directus:11.11.0
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "123456789123456789"
      SECRET: "123456789123456789123456789123456789"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "P@ssw0rd"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"

      # Email Configuration
      EMAIL_FROM: "noreply@yourdomain.com"
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_HOST: "mailpit"
      EMAIL_SMTP_PORT: "1025"
      EMAIL_SMTP_SECURE: "false"

    networks:
      - directus-network
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    networks:
      - directus-network

networks:
  directus-network:
    driver: bridge